---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
  namespace: development
  labels:
    app: quote-service
spec:
  replicas: 2                       # Always ensure that two instances of this app is running
  selector: 
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
      - name: quote-service
        image: datawire/quote:0.5.0 # An Api which serves a random quote called
        resources:
          requests:
            memory: "64Mi"          # Mi stands for Mebibyte which is 2^20 = 1.048.576 bytes 
            cpu: "250m"             # m is for millicores which is 1/1000 of a CPU core. So 250 millicore would be 1/4 of a cpu core
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080